import { Page } from "@playwright/test";

export const locators = {
    infoHeading:          (page: Page) => page.locator('b:has-text("ENTER ACCOUNT INFORMATION")'),
    addressHeading:       (page: Page) => page.locator('b:has-text("ADDRESS INFORMATION")'),
    dateOfBirthDay:       (page: Page) => page.locator('#days'),
    dateOfBirthMonth:     (page: Page) => page.locator('#months'),
    dateOfBirthYear:      (page: Page) => page.locator('#years'),
    zipCodeInput:         (page: Page) => page.locator('#zipcode'),
    MRTitle:              (page: Page) => page.getByRole('radio', { name: 'Mr.' }),
    MSTitle:              (page: Page) => page.getByRole('radio', { name: 'Mrs.' }),
    nameInput:            (page: Page) => page.getByTestId('name'),
    emailInput:           (page: Page) => page.getByTestId('email'),
    passwordInput:        (page: Page) => page.getByTestId('password'),       
    newsletterCheckbox:   (page: Page) => page.getByRole('checkbox', { name: 'newsletter' }),
    offersCheckbox:       (page: Page) => page.getByRole('checkbox', { name: 'optin' }),
    firstNameInput:       (page: Page) => page.getByTestId('first_name'),
    lastNameInput:        (page: Page) => page.getByTestId('last_name'),
    companyInput:         (page: Page) => page.getByTestId('company'),
    address1Input:        (page: Page) => page.getByTestId('address'),
    address2Input:        (page: Page) => page.getByTestId('address2'),
    countrySelect:        (page: Page) => page.getByTestId('country'),
    stateInput:           (page: Page) => page.getByTestId('state'),
    cityInput:            (page: Page) => page.getByTestId('city'),
    mobileNumberInput:    (page: Page) => page.getByTestId('mobile_number'),
    createAccountButton:  (page: Page) => page.getByRole('button', { name: 'Create Account' }),
    loginAccountHeading:  (page: Page) => page.getByText('Login to your account', { exact: true }),
    newUserSignUpHeading: (page: Page) => page.getByText('New User Signup!', { exact: true }),
    loginEmailInput:      (page: Page) => page.getByTestId ('login-email'),
    loginPasswordInput:   (page: Page) => page.getByTestId ('login-password'),
    loginButton:          (page: Page) => page.getByTestId('login-button'),

}